#!/usr/bin/python3

import urllib.request
import boto3


url = 'https://preview.redd.it/this-is-moo-deng-a-two-month-old-pygmy-hippo-from-thailand-v0-1m9wdycvquod1.png?width=640&crop=smart&auto=webp&s=64980ac02f3ca9be13fdcad4714da1aab555c714'
local_filename = 'moodeng.png'
urllib.request.urlretrieve(url, local_filename)

bucket = 'ds2022-cqb3tc'
s3 = boto3.client('s3', region_name="us-east-1")

resp = s3.put_object(
    Body = local_filename,
    Bucket = bucket,
    Key = local_filename,
    ACL = 'public-read'
	)
bucket_name = 'ds2022-cqb3tc'
object_name = 'moodeng.png'
expires_in = 604800

response = s3.generate_presigned_url(
    'get_object',
    Params={'Bucket': bucket_name, 'Key': object_name},
    ExpiresIn=expires_in
    )
print(f"Presigned URL: {response}")
url = https://ds2022-cqb3tc.s3.amazonaws.com/moodeng.png?AWSAccessKeyId=AKIATX3PIDIOGW5SA6XL&Signature=FlQ0KxcceF9jxTSit2MExbIVHPc%3D&Expires=1728252400
